name: build
on: [push]
jobs:
  quality-assurance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Install required Nix packages
        run: nix develop --command true

      - name: Check
        run: nix develop --command cargo check --all-targets

      - name: Check formatting
        run: nix develop --command chkfmt

      - name: Lint
        run: nix develop --command lint

      - name: Test
        run: nix develop --command cargo test

  build-nix-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Build Nix package
        run: nix build

