name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Nix store caching
        uses: actions/cache@v3
        id: nix-cache
        with:
          path: /tmp/nixcache
          key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}

      - name: Install Nix
        uses: cachix/install-nix-action@v22

      - name: Import Nix store cache
        if: steps.nix-cache.outputs.cache-hit == 'true'
        run: nix copy --from /tmp/nixcache --no-check-sigs .#devShells.x86_64-linux.default

      - name: Install required Nix packages
        run: nix develop --command true

      - name: "Export Nix store cache"
        if: steps.nix-cache.outputs.cache-hit != 'true'
        run: nix copy --to /tmp/nixcache --no-check-sigs .#devShells.x86_64-linux.default

      - name: Check
        run: nix develop --command cargo check --all-targets

      - name: Check formatting
        run: nix develop --command chkfmt

      - name: Lint
        run: nix develop --command lint

      - name: Test
        run: nix develop --command cargo test
